"""add family member relationships

Revision ID: bf60dec868de
Revises: 81332b8a3bea
Create Date: 2026-10-06 15:58:39.870449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf60dec868de'
down_revision: Union[str, None] = '81332b8a3bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_invitations', sa.Column('relationship', sa.String(length=50), server_default='other', nullable=False))
    op.add_column('family_members', sa.Column('relationship', sa.String(length=50), server_default='other', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_members', 'relationship')
    op.drop_column('family_invitations', 'relationship')
    # ### end Alembic commands ###
