"""add partial unique index for default categories

Revision ID: 81332b8a3bea
Revises: 90d9b2dc2e57
Create Date: 2026-10-05 22:06:24.826890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81332b8a3bea'
down_revision: Union[str, None] = '90d9b2dc2e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_categories_default_name_type', 'categories', ['name', 'type'], unique=True, postgresql_where=sa.text('family_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_default_name_type', table_name='categories', postgresql_where=sa.text('family_id IS NULL'))
    # ### end Alembic commands ###
